export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";

export const NEXT_STAGE = "NEXT_STAGE";
export const SET_STAGE = "SET_STAGE";
export const SET_COMPLETED_STAGE = "SET_COMPELTED_STAGE";

export const SET_SELECTED_CITY = "SET_SELECTED_CITY";
export const SET_SELECTED_POINT = "SET_SELECTED_POINT";
export const SET_COMPLETE_LOCATION = "SET_COMPELETE_LOCATION";
export const SET_INCOMPLETE_LOCATION = "SET_INCOMPLETE_LOCATION";

export const SET_CHOOSING_CATEGORY = "SET_CHOOSING_CATEGORY";
export const SET_COMPLETE_MODEL = "SET_COMPLETE_MODEL";
export const SET_INCOMPLETE_MODEL = "SET_INCOMPLETE_MODEL";

export const SELECT_MODEL = "SELECT_MODEL";
export const SELECT_COLOR = "SELECT_COLOR";
export const SET_DATE_FROM = "SET_DATE_FROM";
export const SET_DATE_TO = "SET_DATE_TO";
export const SET_TARIFF = "SET_TARIFF";
export const SET_DURATION = "SET_DURATION";
export const SET_PRICE = "SET_PRICE";
export const SET_COMPLETE_ADDPARAMS = "SET_COMPLETE_ADDPARAMS";
export const SET_INCOMPLETE_ADDPARAMS = "SET_INCOMPLETE_ADDPARAMS";
export const TOGGLE_SERVICE = "TOGGLE_SERVICE";
