export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";

export const CHANGE_CURRENT_STAGE = "CHANGE_CURRENT_STAGE";
export const CHANGE_COMPLETED_STAGE = "CHANGE_COMPLETED_STAGE";

export const SET_SELECTED_CITY = "SET_SELECTED_CITY";
export const SET_SELECTED_POINT = "SET_SELECTED_POINT";

export const FILTER_MODELS = "FILTER_MODELS";
export const SELECT_MODEL = "SELECT_MODEL";
